// This file is auto-generated by @hey-api/openapi-ts

export type AnswerCreate = {
    likert_value?: (number | null);
    text_response?: (string | null);
    question_id: string;
};

export type AnswerPublic = {
    likert_value?: (number | null);
    text_response?: (string | null);
    id: string;
    question_id: string;
    question: QuestionPublic;
};

export type AppointmentCreate = {
    appointment_datetime: string;
    title: string;
    description?: (string | null);
    external_calendar_id?: (string | null);
    status?: AppointmentStatus;
    user_id: string;
};

export type AppointmentPublic = {
    appointment_datetime: string;
    title: string;
    description?: (string | null);
    external_calendar_id?: (string | null);
    status?: AppointmentStatus;
    id: string;
    user_id: string;
    created_at: string;
};

export type AppointmentsPublic = {
    data: Array<AppointmentPublic>;
    count: number;
};

export type AppointmentStatus = 'SCHEDULED' | 'COMPLETED' | 'CANCELLED';

export type AppointmentUpdate = {
    appointment_datetime?: (string | null);
    title?: (string | null);
    description?: (string | null);
    external_calendar_id?: (string | null);
    status?: (AppointmentStatus | null);
};

export type AssignmentStatus = 'PENDING' | 'COMPLETED' | 'OVERDUE';

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Body_users_upload_profile_image = {
    file: (Blob | File);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type OrientationCreate = {
    title: string;
    description?: (string | null);
    notes?: (string | null);
    traits?: Array<OrientationTraitCreate>;
};

export type OrientationPublic = {
    title: string;
    description?: (string | null);
    notes?: (string | null);
    id: string;
    owner_id: string;
    traits?: Array<OrientationTraitPublic>;
};

export type OrientationsPublic = {
    data: Array<OrientationPublic>;
    count: number;
};

export type OrientationTraitCreate = {
    name: string;
    value: number;
    description?: (string | null);
};

export type OrientationTraitPublic = {
    name: string;
    value: number;
    description?: (string | null);
    id: string;
};

export type OrientationUpdate = {
    title?: (string | null);
    description?: (string | null);
    notes?: (string | null);
    traits?: (Array<OrientationTraitCreate> | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type QuestionCreate = {
    question_text: string;
    order: number;
    is_required?: boolean;
    scale_type?: ScaleType;
};

export type QuestionnaireAssignmentCreate = {
    questionnaire_id: string;
    user_id: string;
    appointment_id?: (string | null);
    due_date?: (string | null);
};

export type QuestionnaireAssignmentPublic = {
    due_date?: (string | null);
    status?: AssignmentStatus;
    reminder_sent?: boolean;
    id: string;
    questionnaire_id: string;
    user_id: string;
    appointment_id: (string | null);
    assigned_at: string;
    questionnaire: QuestionnaireTemplatePublic;
};

export type QuestionnaireAssignmentsPublic = {
    data: Array<QuestionnaireAssignmentPublic>;
    count: number;
};

export type QuestionnaireResponseCreate = {
    assignment_id: string;
    answers: Array<AnswerCreate>;
};

export type QuestionnaireResponsePublic = {
    total_score?: (number | null);
    manual_score_override?: (number | null);
    id: string;
    assignment_id: string;
    user_id: string;
    completed_at: string;
    answers?: Array<AnswerPublic>;
};

export type QuestionnaireResponsesPublic = {
    data: Array<QuestionnaireResponsePublic>;
    count: number;
};

export type QuestionnaireResponseUpdate = {
    manual_score_override?: (number | null);
};

export type QuestionnaireTemplateCreate = {
    title: string;
    description?: (string | null);
    is_active?: boolean;
    questions?: Array<QuestionCreate>;
};

export type QuestionnaireTemplatePublic = {
    title: string;
    description?: (string | null);
    is_active?: boolean;
    id: string;
    created_by_id: string;
    created_at: string;
    updated_at: string;
    questions?: Array<QuestionPublic>;
};

export type QuestionnaireTemplatesPublic = {
    data: Array<QuestionnaireTemplatePublic>;
    count: number;
};

export type QuestionnaireTemplateUpdate = {
    title?: (string | null);
    description?: (string | null);
    is_active?: boolean;
    questions?: (Array<QuestionCreate> | null);
};

export type QuestionPublic = {
    question_text: string;
    order: number;
    is_required?: boolean;
    scale_type?: ScaleType;
    id: string;
    questionnaire_id: string;
};

export type ScaleType = 'LIKERT_5' | 'LIKERT_7' | 'YES_NO';

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    profile_image?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    profile_image?: (string | null);
    id: string;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    profile_image?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type OrientationsReadOrientationsData = {
    limit?: number;
    skip?: number;
};

export type OrientationsReadOrientationsResponse = (OrientationsPublic);

export type OrientationsCreateOrientationEndpointData = {
    requestBody: OrientationCreate;
};

export type OrientationsCreateOrientationEndpointResponse = (OrientationPublic);

export type OrientationsReadOrientationData = {
    id: string;
};

export type OrientationsReadOrientationResponse = (OrientationPublic);

export type OrientationsUpdateOrientationEndpointData = {
    id: string;
    requestBody: OrientationUpdate;
};

export type OrientationsUpdateOrientationEndpointResponse = (OrientationPublic);

export type OrientationsDeleteOrientationData = {
    id: string;
};

export type OrientationsDeleteOrientationResponse = (Message);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type QuestionnairesReadQuestionnaireTemplatesData = {
    limit?: number;
    skip?: number;
};

export type QuestionnairesReadQuestionnaireTemplatesResponse = (QuestionnaireTemplatesPublic);

export type QuestionnairesCreateQuestionnaireTemplateData = {
    requestBody: QuestionnaireTemplateCreate;
};

export type QuestionnairesCreateQuestionnaireTemplateResponse = (QuestionnaireTemplatePublic);

export type QuestionnairesReadQuestionnaireTemplateData = {
    templateId: string;
};

export type QuestionnairesReadQuestionnaireTemplateResponse = (QuestionnaireTemplatePublic);

export type QuestionnairesUpdateQuestionnaireTemplateData = {
    requestBody: QuestionnaireTemplateUpdate;
    templateId: string;
};

export type QuestionnairesUpdateQuestionnaireTemplateResponse = (QuestionnaireTemplatePublic);

export type QuestionnairesDeleteQuestionnaireTemplateData = {
    templateId: string;
};

export type QuestionnairesDeleteQuestionnaireTemplateResponse = (Message);

export type QuestionnairesCreateAssignmentData = {
    requestBody: QuestionnaireAssignmentCreate;
};

export type QuestionnairesCreateAssignmentResponse = (QuestionnaireAssignmentPublic);

export type QuestionnairesReadMyAssignmentsData = {
    limit?: number;
    skip?: number;
};

export type QuestionnairesReadMyAssignmentsResponse = (QuestionnaireAssignmentsPublic);

export type QuestionnairesReadAssignmentData = {
    assignmentId: string;
};

export type QuestionnairesReadAssignmentResponse = (QuestionnaireAssignmentPublic);

export type QuestionnairesCreateResponseData = {
    requestBody: QuestionnaireResponseCreate;
};

export type QuestionnairesCreateResponseResponse = (QuestionnaireResponsePublic);

export type QuestionnairesReadMyResponsesData = {
    limit?: number;
    skip?: number;
};

export type QuestionnairesReadMyResponsesResponse = (QuestionnaireResponsesPublic);

export type QuestionnairesReadResponseData = {
    responseId: string;
};

export type QuestionnairesReadResponseResponse = (QuestionnaireResponsePublic);

export type QuestionnairesUpdateResponseScoreData = {
    requestBody: QuestionnaireResponseUpdate;
    responseId: string;
};

export type QuestionnairesUpdateResponseScoreResponse = (QuestionnaireResponsePublic);

export type QuestionnairesReadAppointmentsData = {
    limit?: number;
    skip?: number;
};

export type QuestionnairesReadAppointmentsResponse = (AppointmentsPublic);

export type QuestionnairesCreateAppointmentData = {
    requestBody: AppointmentCreate;
};

export type QuestionnairesCreateAppointmentResponse = (AppointmentPublic);

export type QuestionnairesReadAppointmentData = {
    appointmentId: string;
};

export type QuestionnairesReadAppointmentResponse = (AppointmentPublic);

export type QuestionnairesUpdateAppointmentData = {
    appointmentId: string;
    requestBody: AppointmentUpdate;
};

export type QuestionnairesUpdateAppointmentResponse = (AppointmentPublic);

export type QuestionnairesDeleteAppointmentData = {
    appointmentId: string;
};

export type QuestionnairesDeleteAppointmentResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersUploadProfileImageData = {
    formData: Body_users_upload_profile_image;
};

export type UsersUploadProfileImageResponse = (UserPublic);

export type UsersDeleteProfileImageResponse = (UserPublic);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);