// This file is auto-generated by @hey-api/openapi-ts

export type AnalyzeRequest = {
  prompt: string
  details: Array<{
    [key: string]: unknown
  }>
  model?: string | null
  temperature?: number | null
}

export type AnalyzeResponse = {
  answer: string
}

export type AnswerCreate = {
  likert_value?: number | null
  text_response?: string | null
  question_id: string
}

export type AnswerPublic = {
  likert_value?: number | null
  text_response?: string | null
  id: string
  question_id: string
  question: QuestionPublic
}

export type AppointmentCreate = {
  appointment_datetime: string
  title: string
  description?: string | null
  external_calendar_id?: string | null
  status?: AppointmentStatus
  user_id: string
}

export type AppointmentPublic = {
  appointment_datetime: string
  title: string
  description?: string | null
  external_calendar_id?: string | null
  status?: AppointmentStatus
  id: string
  user_id: string
  created_at: string
}

export type AppointmentsPublic = {
  data: Array<AppointmentPublic>
  count: number
}

export type AppointmentStatus = "SCHEDULED" | "COMPLETED" | "CANCELLED"

export type AppointmentUpdate = {
  appointment_datetime?: string | null
  title?: string | null
  description?: string | null
  external_calendar_id?: string | null
  status?: AppointmentStatus | null
}

export type AssessmentSource =
  | "self_report"
  | "goal_adherence"
  | "cognition_inference"

export type AssignmentStatus = "PENDING" | "COMPLETED" | "OVERDUE"

export type Body_login_login_access_token = {
  grant_type?: string | null
  username: string
  password: string
  scope?: string
  client_id?: string | null
  client_secret?: string | null
}

export type Body_users_upload_profile_image = {
  file: Blob | File
}

/**
 * Response model for chat history.
 */
export type ChatHistoryResponse = {
  history: Array<{
    [key: string]: string
  }>
  message_count: number
}

export type CheckinPublic = {
  id: string
  type: "morning" | "evening"
  text: string
  reply: string
  created_at: string
  alignment_score?: number | null
  onboarding_id?: string | null
  morning_id?: string | null
}

export type type = "morning" | "evening"

export type CheckinRequest = {
  type: "morning" | "evening"
  text: string
}

export type CheckinResponse = {
  reply: string
  checkin_id: string
}

export type CheckinsPublic = {
  data: Array<CheckinPublic>
  count: number
}

export type CheckinUpdate = {
  text: string
}

/**
 * Response model for clearing history.
 */
export type ClearHistoryResponse = {
  messages_deleted: number
}

export type ConceptDimensionPublic = {
  name: string
  value: number
  source: DimensionSource
  id: string
  user_id: string
  last_updated: string
}

export type CycleStatus = "in_progress" | "met" | "missed" | "adjusted"

export type DashboardSummary = {
  goal_completion_rate?: number | null
  stability_score?: number | null
  ici_value?: number | null
  pillar_balance?: number | null
  streak_best?: number | null
  trajectory_direction?: number | null
}

export type DimensionSource =
  | "questionnaire"
  | "observation"
  | "adherence"
  | "computed"

export type Engine89ResultCreate = {
  kind: string
  schema_version?: string
  payload: {
    [key: string]: unknown
  }
  subject_hash?: string | null
}

export type Engine89ResultPublic = {
  kind: string
  schema_version?: string
  payload: {
    [key: string]: unknown
  }
  id: string
  owner_id: string
  created_at: string
}

export type Engine89ResultsPublic = {
  data: Array<Engine89ResultPublic>
  count: number
}

export type EscalationReason =
  | "low_stability"
  | "identity_drift"
  | "repeated_missed_cycles"
  | "cognitive_overload"
  | "pillar_imbalance"

export type EscalationSignalPublic = {
  id: string
  user_id: string
  reason: EscalationReason
  stability_score: number
  drift_score: number | null
  details: {
    [key: string]: unknown
  }
  generated_at: string
  acknowledged: boolean
  acknowledged_at: string | null
}

export type EscalationsPublic = {
  data: Array<EscalationSignalPublic>
  count: number
}

export type GoalCategory =
  | "exercise"
  | "nutrition"
  | "sleep"
  | "mindfulness"
  | "social"
  | "learning"
  | "custom"

export type GoalCreate = {
  category: GoalCategory
  title: string
  description?: string | null
  target_value: number
  target_unit: string
  intensity_level?: number
  time_horizon?: string
  parent_goal_id?: string | null
}

export type GoalCycleCreate = {
  goal_id: string
  cycle_id?: string | null
  target_value?: number | null
  intensity_level?: number | null
}

export type GoalCyclePublic = {
  id: string
  goal_id: string
  cycle_id?: string | null
  target_value: number
  intensity_level: number
  achieved_value: number
  status: CycleStatus
  adjustment_note?: string | null
  created_at: string
  completed_at?: string | null
}

export type GoalLogCreate = {
  date: string
  completed: boolean
  value?: number | null
  intensity_actual?: number | null
  note?: string | null
}

export type GoalLogPublic = {
  id: string
  goal_cycle_id: string
  date: string
  completed: boolean
  value?: number | null
  intensity_actual?: number | null
  note?: string | null
  logged_at: string
}

export type GoalPublic = {
  id: string
  user_id: string
  category: GoalCategory
  title: string
  description?: string | null
  target_value: number
  target_unit: string
  intensity_level: number
  time_horizon: string
  parent_goal_id?: string | null
  status: GoalStatus
  created_at: string
  updated_at: string
}

export type GoalsPublic = {
  data: Array<GoalPublic>
  count: number
}

export type GoalStatus = "active" | "paused" | "completed" | "archived"

export type GoalUpdate = {
  category?: GoalCategory | null
  title?: string | null
  description?: string | null
  target_value?: number | null
  target_unit?: string | null
  intensity_level?: number | null
  time_horizon?: string | null
  parent_goal_id?: string | null
}

export type HabitLogCreate = {
  date: string
  completed: boolean
  value?: number | null
  intensity_actual?: number | null
  note?: string | null
}

export type HabitLogPublic = {
  id: string
  habit_id: string
  date: string
  completed: boolean
  value: number | null
  intensity_actual: number | null
  note: string | null
  logged_at: string
}

export type HabitPublic = {
  id: string
  user_id: string
  origin_goal_id: string | null
  category: GoalCategory
  title: string
  frequency: number
  intensity_level: number
  established_at: string
  streak_weeks: number
  status: HabitStatus
}

export type HabitsPublic = {
  data: Array<HabitPublic>
  count: number
}

export type HabitStatus = "active" | "paused" | "broken"

export type HealthPillarPublic = {
  id: string
  health_profile_id: string
  pillar_type: PillarType
  current_level: number
  sub_axes: {
    [key: string]: unknown
  }
}

export type HealthProfilePublic = {
  id: string
  user_id: string
  primary_focus: PillarType
  balance_score: number
  last_assessed: string | null
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type IdentityConsistencyIndexPublic = {
  id: string
  user_id: string
  value: number
  components: {
    [key: string]: unknown
  }
  computed_at: string
  cycle_id: string | null
}

export type MealEntryCreate = {
  day_of_week: number
  meal_type: MealType
  description: string
  recipe_ref?: string | null
  prep_notes?: string | null
}

export type MealEntryPublic = {
  id: string
  meal_plan_id: string
  day_of_week: number
  meal_type: MealType
  description: string
  recipe_ref?: string | null
  prep_notes?: string | null
}

export type MealPlanCreate = {
  week_start: string
  notes?: string | null
}

export type MealPlanPublic = {
  id: string
  user_id: string
  week_start: string
  status: MealPlanStatus
  notes?: string | null
  created_at: string
}

export type MealPlansPublic = {
  data: Array<MealPlanPublic>
  count: number
}

export type MealPlanStatus = "draft" | "active" | "completed"

export type MealPlanUpdate = {
  week_start?: string | null
  notes?: string | null
  status?: MealPlanStatus | null
}

export type MealType = "breakfast" | "lunch" | "dinner" | "snack"

export type Message = {
  message: string
}

export type MetricDataPointPublic = {
  id: string
  series_id: string
  timestamp: string
  value: number
  metadata_?: {
    [key: string]: unknown
  } | null
}

export type MetricTimeSeriesPublic = {
  id: string
  user_id: string
  metric_name: string
  category: string
  aggregation_period: string
}

export type NewPassword = {
  token: string
  new_password: string
}

export type NutritionLogCreate = {
  date: string
  meal_type: MealType
  completed: boolean
  description?: string | null
  nutrients?: {
    [key: string]: unknown
  } | null
}

export type NutritionLogPublic = {
  id: string
  user_id: string
  date: string
  meal_type: MealType
  completed: boolean
  description?: string | null
  nutrients?: {
    [key: string]: unknown
  } | null
  logged_at: string
}

export type ObservationContext =
  | "daily_log"
  | "weekly_reflection"
  | "goal_note"
  | "habit_note"

export type PillarAssessmentCreate = {
  level: number
  sub_axes_snapshot: {
    [key: string]: unknown
  }
  source?: AssessmentSource
}

export type PillarAssessmentPublic = {
  id: string
  pillar_id: string
  assessed_at: string
  level: number
  sub_axes_snapshot: {
    [key: string]: unknown
  }
  source: AssessmentSource
}

export type PillarType = "endurance" | "strength" | "mobility"

export type PrivateUserCreate = {
  email: string
  password: string
  full_name: string
  is_verified?: boolean
}

export type QualitativeObservationCreate = {
  text: string
  context: ObservationContext
}

export type QualitativeObservationPublic = {
  id: string
  user_id: string
  text: string
  context: ObservationContext
  decoded_dimensions: {
    [key: string]: unknown
  } | null
  decoded_by: string
  observed_at: string
}

export type QuestionCreate = {
  question_text: string
  order: number
  is_required?: boolean
  scale_type?: ScaleType
  custom_min_value?: number | null
  custom_max_value?: number | null
  custom_unit_label?: string | null
}

export type QuestionnaireAssignmentBulkCreate = {
  questionnaire_id: string
  user_ids: Array<string>
  appointment_id?: string | null
  due_date?: string | null
}

export type QuestionnaireAssignmentCreate = {
  questionnaire_id: string
  user_id: string
  appointment_id?: string | null
  due_date?: string | null
}

export type QuestionnaireAssignmentPublic = {
  due_date?: string | null
  status?: AssignmentStatus
  reminder_sent?: boolean
  saved_progress?: {
    [key: string]: unknown
  } | null
  id: string
  questionnaire_id: string
  user_id: string
  appointment_id: string | null
  assigned_at: string
  questionnaire: QuestionnaireTemplatePublic
}

export type QuestionnaireAssignmentsPublic = {
  data: Array<QuestionnaireAssignmentPublic>
  count: number
}

export type QuestionnaireResponseCreate = {
  assignment_id: string
  answers: Array<AnswerCreate>
}

export type QuestionnaireResponsePublic = {
  total_score?: number | null
  manual_score_override?: number | null
  id: string
  assignment_id: string
  user_id: string
  completed_at: string
  answers?: Array<AnswerPublic>
}

export type QuestionnaireResponsesPublic = {
  data: Array<QuestionnaireResponsePublic>
  count: number
}

export type QuestionnaireResponseUpdate = {
  manual_score_override?: number | null
}

export type QuestionnaireTemplateCreate = {
  title: string
  description?: string | null
  is_active?: boolean
  questions?: Array<QuestionCreate>
}

export type QuestionnaireTemplatePublic = {
  title: string
  description?: string | null
  is_active?: boolean
  id: string
  created_by_id: string
  created_at: string
  updated_at: string
  questions?: Array<QuestionPublic>
}

export type QuestionnaireTemplatesPublic = {
  data: Array<QuestionnaireTemplatePublic>
  count: number
}

export type QuestionnaireTemplateUpdate = {
  title?: string | null
  description?: string | null
  is_active?: boolean
  questions?: Array<QuestionCreate> | null
}

export type QuestionPublic = {
  question_text: string
  order: number
  is_required?: boolean
  scale_type?: ScaleType
  custom_min_value?: number | null
  custom_max_value?: number | null
  custom_unit_label?: string | null
  id: string
  questionnaire_id: string
}

export type ScaleType =
  | "LIKERT_5"
  | "LIKERT_7"
  | "YES_NO"
  | "CUSTOM_NUMERIC"
  | "TEXT"
  | "FREQUENCY"
  | "DOMAIN_RATING"

export type SelfConceptSnapshotPublic = {
  id: string
  user_id: string
  dimensions: {
    [key: string]: unknown
  }
  identity_consistency_index: number | null
  computed_at: string
  cycle_id: string | null
}

export type StabilityScorePublic = {
  id: string
  user_id: string
  value: number
  components: {
    [key: string]: unknown
  }
  computed_at: string
  cycle_id: string | null
}

export type Token = {
  access_token: string
  token_type?: string
}

export type TrajectoryHistoryPublic = {
  data: Array<TrajectoryVectorPublic>
  count: number
}

export type TrajectoryVectorPublic = {
  id: string
  user_id: string
  stability_trend: number
  intensity_trend: number
  identity_alignment_trend: number
  pillar_balance: number
  overall_trajectory: number
  computed_at: string
  cycle_id: string | null
}

export type UpdatePassword = {
  current_password: string
  new_password: string
}

export type UserCreate = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  profile_image?: string | null
  onboarding_completed_at?: string | null
  can_delete_account?: boolean
  password: string
}

export type UserPublic = {
  email: string
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  profile_image?: string | null
  onboarding_completed_at?: string | null
  can_delete_account?: boolean
  id: string
}

export type UserRegister = {
  email: string
  password: string
  full_name?: string | null
}

export type UserResourceProfilePublic = {
  id: string
  user_id: string
  weekly_available_hours: number
  equipment_access: Array<unknown>
  cooking_access: string
  time_variability: number
  stress_baseline: number
  updated_at: string
}

export type UserResourceProfileUpdate = {
  weekly_available_hours?: number | null
  equipment_access?: Array<string> | null
  cooking_access?: string | null
  time_variability?: number | null
  stress_baseline?: number | null
}

export type UsersPublic = {
  data: Array<UserPublic>
  count: number
}

export type UserUpdate = {
  email?: string | null
  is_active?: boolean
  is_superuser?: boolean
  full_name?: string | null
  profile_image?: string | null
  onboarding_completed_at?: string | null
  can_delete_account?: boolean
  password?: string | null
}

export type UserUpdateMe = {
  full_name?: string | null
  email?: string | null
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type WeeklyCyclePublic = {
  id: string
  user_id: string
  week_start: string
  week_end: string
  status: WeeklyCycleStatus
  created_at: string
}

export type WeeklyCyclesPublic = {
  data: Array<WeeklyCyclePublic>
  count: number
}

export type WeeklyCycleStatus = "upcoming" | "active" | "review" | "completed"

export type WeeklyReviewPublic = {
  id: string
  cycle_id: string
  goals_met: number
  goals_missed: number
  goals_adjusted: number
  qualitative_reflection?: string | null
  reflection_energy_level?: number | null
  reflection_motivation?: number | null
  reflection_perceived_control?: number | null
  adjustments_made?: {
    [key: string]: unknown
  } | null
  self_concept_delta?: {
    [key: string]: unknown
  } | null
  cognition_session_id?: string | null
  completed_at?: string | null
}

export type WeeklyReviewUpdate = {
  qualitative_reflection?: string | null
  reflection_energy_level?: number | null
  reflection_motivation?: number | null
  reflection_perceived_control?: number | null
  adjustments_made?: Array<{
    [key: string]: unknown
  }> | null
  self_concept_delta?: {
    [key: string]: unknown
  } | null
  cognition_session_id?: string | null
}

export type AiChatWithAiData = {
  requestBody: Message
}

export type AiChatWithAiResponse = Message

export type AiAnalyzeWithAiData = {
  requestBody: AnalyzeRequest
}

export type AiAnalyzeWithAiResponse = AnalyzeResponse

export type AiGetChatHistoryResponse = ChatHistoryResponse

export type AiClearChatHistoryResponse = ClearHistoryResponse

export type CheckinsCreateCheckinData = {
  requestBody: CheckinRequest
}

export type CheckinsCreateCheckinResponse = CheckinResponse

export type CheckinsReadCheckinsData = {
  limit?: number
  skip?: number
  type?: "morning" | "evening" | null
}

export type CheckinsReadCheckinsResponse = CheckinsPublic

export type CheckinsReadCheckinTimelineData = {
  days?: number
}

export type CheckinsReadCheckinTimelineResponse = CheckinsPublic

export type CheckinsReadCheckinData = {
  checkinId: string
}

export type CheckinsReadCheckinResponse = CheckinPublic

export type CheckinsUpdateCheckinData = {
  checkinId: string
  requestBody: CheckinUpdate
}

export type CheckinsUpdateCheckinResponse = CheckinPublic

export type CheckinsDeleteCheckinData = {
  checkinId: string
}

export type CheckinsDeleteCheckinResponse = Message

export type Engine89ExportForEngine89Data = {
  kind?: string | null
}

export type Engine89ExportForEngine89Response = {
  [key: string]: unknown
}

export type Engine89ImportEngine89ResultsData = {
  requestBody: Array<Engine89ResultCreate>
}

export type Engine89ImportEngine89ResultsResponse = Message

export type Engine89RunEngine89Data = {
  kind?: string | null
}

export type Engine89RunEngine89Response = Message

export type Engine89ReadEngine89ResultsData = {
  limit?: number
  skip?: number
}

export type Engine89ReadEngine89ResultsResponse = Engine89ResultsPublic

export type GoalScaffoldCreateGoalData = {
  requestBody: GoalCreate
}

export type GoalScaffoldCreateGoalResponse = GoalPublic

export type GoalScaffoldListGoalsData = {
  includeArchived?: boolean
  limit?: number
  skip?: number
}

export type GoalScaffoldListGoalsResponse = GoalsPublic

export type GoalScaffoldGetGoalData = {
  goalId: string
}

export type GoalScaffoldGetGoalResponse = GoalPublic

export type GoalScaffoldUpdateGoalData = {
  goalId: string
  requestBody: GoalUpdate
}

export type GoalScaffoldUpdateGoalResponse = GoalPublic

export type GoalScaffoldArchiveGoalData = {
  goalId: string
}

export type GoalScaffoldArchiveGoalResponse = GoalPublic

export type GoalScaffoldCreateGoalCycleData = {
  goalId: string
  requestBody: GoalCycleCreate
}

export type GoalScaffoldCreateGoalCycleResponse = GoalCyclePublic

export type GoalScaffoldListGoalCyclesData = {
  goalId: string
}

export type GoalScaffoldListGoalCyclesResponse = Array<GoalCyclePublic>

export type GoalScaffoldRecordLogData = {
  cycleId: string
  requestBody: GoalLogCreate
}

export type GoalScaffoldRecordLogResponse = GoalLogPublic

export type GoalScaffoldCompleteCycleData = {
  cycleId: string
}

export type GoalScaffoldCompleteCycleResponse = GoalCyclePublic

export type GoalScaffoldGoalSummaryData = {
  goalId: string
}

export type GoalScaffoldGoalSummaryResponse = unknown

export type GoalScaffoldGetLatestSnapshotResponse =
  SelfConceptSnapshotPublic | null

export type GoalScaffoldGetDimensionsResponse = Array<ConceptDimensionPublic>

export type GoalScaffoldRecordObservationData = {
  requestBody: QualitativeObservationCreate
}

export type GoalScaffoldRecordObservationResponse = QualitativeObservationPublic

export type GoalScaffoldGetSnapshotHistoryData = {
  limit?: number
  offset?: number
}

export type GoalScaffoldGetSnapshotHistoryResponse =
  Array<SelfConceptSnapshotPublic>

export type GoalScaffoldGetLatestIciResponse =
  IdentityConsistencyIndexPublic | null

export type GoalScaffoldListHabitsData = {
  limit?: number
  skip?: number
}

export type GoalScaffoldListHabitsResponse = HabitsPublic

export type GoalScaffoldGetHabitData = {
  habitId: string
}

export type GoalScaffoldGetHabitResponse = HabitPublic

export type GoalScaffoldLogHabitData = {
  habitId: string
  requestBody: HabitLogCreate
}

export type GoalScaffoldLogHabitResponse = HabitLogPublic

export type GoalScaffoldGetStreakData = {
  habitId: string
}

export type GoalScaffoldGetStreakResponse = {
  [key: string]: number
}

export type GoalScaffoldGraduateGoalData = {
  goalId: string
}

export type GoalScaffoldGraduateGoalResponse = HabitPublic

export type GoalScaffoldGetHealthProfileResponse = HealthProfilePublic

export type GoalScaffoldRecordAssessmentData = {
  pillarId: string
  requestBody: PillarAssessmentCreate
}

export type GoalScaffoldRecordAssessmentResponse = PillarAssessmentPublic

export type GoalScaffoldGetPillarsResponse = Array<HealthPillarPublic>

export type GoalScaffoldGetPriorityResponse = PillarType

export type GoalScaffoldGetPillarHistoryData = {
  limit?: number
  offset?: number
  pillarId: string
}

export type GoalScaffoldGetPillarHistoryResponse = Array<PillarAssessmentPublic>

export type GoalScaffoldCreateMealPlanData = {
  requestBody: MealPlanCreate
}

export type GoalScaffoldCreateMealPlanResponse = MealPlanPublic

export type GoalScaffoldListMealPlansData = {
  limit?: number
  skip?: number
}

export type GoalScaffoldListMealPlansResponse = MealPlansPublic

export type GoalScaffoldGetMealPlanData = {
  planId: string
}

export type GoalScaffoldGetMealPlanResponse = MealPlanPublic

export type GoalScaffoldUpdateMealPlanData = {
  planId: string
  requestBody: MealPlanUpdate
}

export type GoalScaffoldUpdateMealPlanResponse = MealPlanPublic

export type GoalScaffoldAddMealEntryData = {
  planId: string
  requestBody: MealEntryCreate
}

export type GoalScaffoldAddMealEntryResponse = MealEntryPublic

export type GoalScaffoldActivateMealPlanData = {
  planId: string
}

export type GoalScaffoldActivateMealPlanResponse = MealPlanPublic

export type GoalScaffoldRecordNutritionLogData = {
  requestBody: NutritionLogCreate
}

export type GoalScaffoldRecordNutritionLogResponse = NutritionLogPublic

export type GoalScaffoldWeeklySummaryData = {
  /**
   * ISO date for the Monday of the target week
   */
  weekStart: string
}

export type GoalScaffoldWeeklySummaryResponse = unknown

export type GoalScaffoldGetCurrentCycleResponse = WeeklyCyclePublic

export type GoalScaffoldListPastCyclesData = {
  limit?: number
  skip?: number
}

export type GoalScaffoldListPastCyclesResponse = WeeklyCyclesPublic

export type GoalScaffoldGetCycleData = {
  cycleId: string
}

export type GoalScaffoldGetCycleResponse = WeeklyCyclePublic

export type GoalScaffoldStartReviewData = {
  cycleId: string
}

export type GoalScaffoldStartReviewResponse = WeeklyReviewPublic

export type GoalScaffoldCompleteReviewData = {
  requestBody: WeeklyReviewUpdate
  reviewId: string
}

export type GoalScaffoldCompleteReviewResponse = WeeklyReviewPublic

export type GoalScaffoldGetReviewData = {
  cycleId: string
}

export type GoalScaffoldGetReviewResponse = WeeklyReviewPublic

export type GoalScaffoldGetCurrentStabilityResponse =
  StabilityScorePublic | null

export type GoalScaffoldGetStabilityHistoryData = {
  limit?: number
  skip?: number
}

export type GoalScaffoldGetStabilityHistoryResponse =
  Array<StabilityScorePublic>

export type GoalScaffoldGetEscalationsResponse = EscalationsPublic

export type GoalScaffoldAcknowledgeEscalationData = {
  escalationId: string
}

export type GoalScaffoldAcknowledgeEscalationResponse = EscalationSignalPublic

export type GoalScaffoldGetResourceProfileResponse = UserResourceProfilePublic

export type GoalScaffoldUpdateResourceProfileData = {
  requestBody: UserResourceProfileUpdate
}

export type GoalScaffoldUpdateResourceProfileResponse =
  UserResourceProfilePublic

export type GoalScaffoldGetCurrentTrajectoryResponse = TrajectoryVectorPublic

export type GoalScaffoldGetTrajectoryHistoryData = {
  limit?: number
  offset?: number
}

export type GoalScaffoldGetTrajectoryHistoryResponse = TrajectoryHistoryPublic

export type GoalScaffoldGetMetricSeriesData = {
  limit?: number
  metricName: string
}

export type GoalScaffoldGetMetricSeriesResponse = Array<MetricDataPointPublic>

export type GoalScaffoldGetDashboardResponse = DashboardSummary

export type GoalScaffoldListAvailableSeriesResponse =
  Array<MetricTimeSeriesPublic>

export type LoginLoginAccessTokenData = {
  formData: Body_login_login_access_token
}

export type LoginLoginAccessTokenResponse = Token

export type LoginTestTokenResponse = UserPublic

export type LoginRecoverPasswordData = {
  email: string
}

export type LoginRecoverPasswordResponse = Message

export type LoginResetPasswordData = {
  requestBody: NewPassword
}

export type LoginResetPasswordResponse = Message

export type LoginRecoverPasswordHtmlContentData = {
  email: string
}

export type LoginRecoverPasswordHtmlContentResponse = string

export type PrivateCreateUserData = {
  requestBody: PrivateUserCreate
}

export type PrivateCreateUserResponse = UserPublic

export type QuestionnairesReadQuestionnaireTemplatesData = {
  limit?: number
  skip?: number
}

export type QuestionnairesReadQuestionnaireTemplatesResponse =
  QuestionnaireTemplatesPublic

export type QuestionnairesCreateQuestionnaireTemplateData = {
  requestBody: QuestionnaireTemplateCreate
}

export type QuestionnairesCreateQuestionnaireTemplateResponse =
  QuestionnaireTemplatePublic

export type QuestionnairesReadQuestionnaireTemplateData = {
  templateId: string
}

export type QuestionnairesReadQuestionnaireTemplateResponse =
  QuestionnaireTemplatePublic

export type QuestionnairesUpdateQuestionnaireTemplateData = {
  requestBody: QuestionnaireTemplateUpdate
  templateId: string
}

export type QuestionnairesUpdateQuestionnaireTemplateResponse =
  QuestionnaireTemplatePublic

export type QuestionnairesDeleteQuestionnaireTemplateData = {
  templateId: string
}

export type QuestionnairesDeleteQuestionnaireTemplateResponse = Message

export type QuestionnairesCreateAssignmentData = {
  requestBody: QuestionnaireAssignmentCreate
}

export type QuestionnairesCreateAssignmentResponse =
  QuestionnaireAssignmentPublic

export type QuestionnairesReadAllAssignmentsData = {
  limit?: number
  questionnaireId?: string | null
  skip?: number
}

export type QuestionnairesReadAllAssignmentsResponse =
  QuestionnaireAssignmentsPublic

export type QuestionnairesCreateBulkAssignmentsData = {
  requestBody: QuestionnaireAssignmentBulkCreate
}

export type QuestionnairesCreateBulkAssignmentsResponse = unknown

export type QuestionnairesReadMyAssignmentsData = {
  limit?: number
  skip?: number
}

export type QuestionnairesReadMyAssignmentsResponse =
  QuestionnaireAssignmentsPublic

export type QuestionnairesReadAssignmentData = {
  assignmentId: string
}

export type QuestionnairesReadAssignmentResponse = QuestionnaireAssignmentPublic

export type QuestionnairesDeleteAssignmentData = {
  assignmentId: string
}

export type QuestionnairesDeleteAssignmentResponse = Message

export type QuestionnairesUpdateAssignmentProgressData = {
  assignmentId: string
  requestBody: {
    [key: string]: unknown
  }
}

export type QuestionnairesUpdateAssignmentProgressResponse =
  QuestionnaireAssignmentPublic

export type QuestionnairesCreateResponseData = {
  requestBody: QuestionnaireResponseCreate
}

export type QuestionnairesCreateResponseResponse = QuestionnaireResponsePublic

export type QuestionnairesReadMyResponsesData = {
  limit?: number
  skip?: number
}

export type QuestionnairesReadMyResponsesResponse = QuestionnaireResponsesPublic

export type QuestionnairesReadResponseData = {
  responseId: string
}

export type QuestionnairesReadResponseResponse = QuestionnaireResponsePublic

export type QuestionnairesUpdateResponseScoreData = {
  requestBody: QuestionnaireResponseUpdate
  responseId: string
}

export type QuestionnairesUpdateResponseScoreResponse =
  QuestionnaireResponsePublic

export type QuestionnairesReadAppointmentsData = {
  limit?: number
  skip?: number
}

export type QuestionnairesReadAppointmentsResponse = AppointmentsPublic

export type QuestionnairesCreateAppointmentData = {
  requestBody: AppointmentCreate
}

export type QuestionnairesCreateAppointmentResponse = AppointmentPublic

export type QuestionnairesReadAppointmentData = {
  appointmentId: string
}

export type QuestionnairesReadAppointmentResponse = AppointmentPublic

export type QuestionnairesUpdateAppointmentData = {
  appointmentId: string
  requestBody: AppointmentUpdate
}

export type QuestionnairesUpdateAppointmentResponse = AppointmentPublic

export type QuestionnairesDeleteAppointmentData = {
  appointmentId: string
}

export type QuestionnairesDeleteAppointmentResponse = Message

export type UsersReadUsersData = {
  limit?: number
  skip?: number
}

export type UsersReadUsersResponse = UsersPublic

export type UsersCreateUserData = {
  requestBody: UserCreate
}

export type UsersCreateUserResponse = UserPublic

export type UsersReadUserMeResponse = UserPublic

export type UsersDeleteUserMeResponse = Message

export type UsersUpdateUserMeData = {
  requestBody: UserUpdateMe
}

export type UsersUpdateUserMeResponse = UserPublic

export type UsersUpdatePasswordMeData = {
  requestBody: UpdatePassword
}

export type UsersUpdatePasswordMeResponse = Message

export type UsersUploadProfileImageData = {
  formData: Body_users_upload_profile_image
}

export type UsersUploadProfileImageResponse = UserPublic

export type UsersDeleteProfileImageResponse = UserPublic

export type UsersRegisterUserData = {
  requestBody: UserRegister
}

export type UsersRegisterUserResponse = UserPublic

export type UsersReadUserByIdData = {
  userId: string
}

export type UsersReadUserByIdResponse = UserPublic

export type UsersUpdateUserData = {
  requestBody: UserUpdate
  userId: string
}

export type UsersUpdateUserResponse = UserPublic

export type UsersDeleteUserData = {
  userId: string
}

export type UsersDeleteUserResponse = Message

export type UtilsTestEmailData = {
  emailTo: string
}

export type UtilsTestEmailResponse = Message

export type UtilsHealthCheckResponse = boolean
