"""add_can_delete_account_to_user

Revision ID: 25804c55c61c
Revises: dab98d5cebd7
Create Date: 2026-03-15 22:03:16.207614

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '25804c55c61c'
down_revision = 'dab98d5cebd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('can_delete_account', sa.Boolean(), nullable=True))
    op.execute('UPDATE "user" SET can_delete_account = FALSE')
    op.alter_column('user', 'can_delete_account', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'can_delete_account')
    # ### end Alembic commands ###
