"""fitness bounded context tables

Revision ID: 3af11da704ca
Revises: 89376142313e
Create Date: 2026-02-27 14:55:39.797826

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '3af11da704ca'
down_revision = '89376142313e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gs_exercise_definition',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('domain', sa.Enum('ENDURANCE', 'SKELETAL_MUSCULAR', 'MOBILITY', name='fitnessdomain'), nullable=False),
    sa.Column('subdomain', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('mechanical_demand', sa.Float(), nullable=False),
    sa.Column('metabolic_demand', sa.Float(), nullable=False),
    sa.Column('recovery_cost', sa.Float(), nullable=False),
    sa.Column('time_requirement_min', sa.Integer(), nullable=False),
    sa.Column('time_requirement_typical', sa.Integer(), nullable=False),
    sa.Column('equipment_required', sa.JSON(), nullable=False),
    sa.Column('space_required', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('skill_complexity', sa.Float(), nullable=False),
    sa.Column('psych_barrier', sa.Float(), nullable=False),
    sa.Column('impact_profile', sa.JSON(), nullable=False),
    sa.Column('contraindications', sa.JSON(), nullable=False),
    sa.Column('scalability', sa.JSON(), nullable=False),
    sa.Column('library_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gs_exercise_definition_library_version'), 'gs_exercise_definition', ['library_version'], unique=False)
    op.create_index(op.f('ix_gs_exercise_definition_name'), 'gs_exercise_definition', ['name'], unique=False)
    op.create_table('goal_scaffold_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('emitted_at', sa.DateTime(), nullable=False),
    sa.Column('schema_version', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_scaffold_event_domain'), 'goal_scaffold_event', ['domain'], unique=False)
    op.create_index(op.f('ix_goal_scaffold_event_emitted_at'), 'goal_scaffold_event', ['emitted_at'], unique=False)
    op.create_index(op.f('ix_goal_scaffold_event_event_type'), 'goal_scaffold_event', ['event_type'], unique=False)
    op.create_index(op.f('ix_goal_scaffold_event_processed'), 'goal_scaffold_event', ['processed'], unique=False)
    op.create_table('gs_concept_dimension',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('QUESTIONNAIRE', 'OBSERVATION', 'ADHERENCE', 'COMPUTED', name='dimensionsource'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gs_escalation_signal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Enum('LOW_STABILITY', 'IDENTITY_DRIFT', 'REPEATED_MISSED_CYCLES', 'COGNITIVE_OVERLOAD', 'PILLAR_IMBALANCE', name='escalationreason'), nullable=False),
    sa.Column('stability_score', sa.Float(), nullable=False),
    sa.Column('drift_score', sa.Float(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gs_goal',
    sa.Column('category', sa.Enum('EXERCISE', 'NUTRITION', 'SLEEP', 'MINDFULNESS', 'SOCIAL', 'LEARNING', 'CUSTOM', name='goalcategory'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('target_unit', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('intensity_level', sa.Integer(), nullable=False),
    sa.Column('time_horizon', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('parent_goal_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', 'ARCHIVED', name='goalstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_goal_id'], ['gs_goal.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gs_health_profile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('primary_focus', sa.Enum('ENDURANCE', 'STRENGTH', 'MOBILITY', name='pillartype'), nullable=False),
    sa.Column('balance_score', sa.Float(), nullable=False),
    sa.Column('last_assessed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('gs_meal_plan',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'COMPLETED', name='mealplanstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gs_metric_time_series',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('metric_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('aggregation_period', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gs_metric_time_series_metric_name'), 'gs_metric_time_series', ['metric_name'], unique=False)
    op.create_table('gs_nutrition_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.Enum('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK', name='mealtype'), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('nutrients', sa.JSON(), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gs_qualitative_observation',
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('context', sa.Enum('DAILY_LOG', 'WEEKLY_REFLECTION', 'GOAL_NOTE', 'HABIT_NOTE', name='observationcontext'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('decoded_dimensions', sa.JSON(), nullable=True),
    sa.Column('decoded_by', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gs_user_resource_profile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('weekly_available_hours', sa.Float(), nullable=False),
    sa.Column('equipment_access', sa.JSON(), nullable=True),
    sa.Column('cooking_access', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('time_variability', sa.Float(), nullable=False),
    sa.Column('stress_baseline', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('gs_weekly_cycle',
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('UPCOMING', 'ACTIVE', 'REVIEW', 'COMPLETED', name='weeklycyclestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gs_goal_cycle',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('goal_id', sa.Uuid(), nullable=False),
    sa.Column('cycle_id', sa.Uuid(), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('intensity_level', sa.Integer(), nullable=False),
    sa.Column('achieved_value', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'MET', 'MISSED', 'ADJUSTED', name='cyclestatus'), nullable=False),
    sa.Column('adjustment_note', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['gs_weekly_cycle.id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['gs_goal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gs_habit',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('origin_goal_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.Enum('EXERCISE', 'NUTRITION', 'SLEEP', 'MINDFULNESS', 'SOCIAL', 'LEARNING', 'CUSTOM', name='goalcategory'), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('intensity_level', sa.Integer(), nullable=False),
    sa.Column('established_at', sa.DateTime(), nullable=False),
    sa.Column('streak_weeks', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'BROKEN', name='habitstatus'), nullable=False),
    sa.ForeignKeyConstraint(['origin_goal_id'], ['gs_goal.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gs_health_pillar',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('health_profile_id', sa.Uuid(), nullable=False),
    sa.Column('pillar_type', sa.Enum('ENDURANCE', 'STRENGTH', 'MOBILITY', name='pillartype'), nullable=False),
    sa.Column('current_level', sa.Float(), nullable=False),
    sa.Column('sub_axes', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['health_profile_id'], ['gs_health_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gs_identity_consistency_index',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('cycle_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['gs_weekly_cycle.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gs_meal_entry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('meal_plan_id', sa.Uuid(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.Enum('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK', name='mealtype'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('recipe_ref', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('prep_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['gs_meal_plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gs_metric_data_point',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('series_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['series_id'], ['gs_metric_time_series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gs_self_concept_snapshot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('dimensions', sa.JSON(), nullable=False),
    sa.Column('identity_consistency_index', sa.Float(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('cycle_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['gs_weekly_cycle.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gs_stability_score',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('cycle_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['gs_weekly_cycle.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gs_trajectory_vector',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('stability_trend', sa.Float(), nullable=False),
    sa.Column('intensity_trend', sa.Float(), nullable=False),
    sa.Column('identity_alignment_trend', sa.Float(), nullable=False),
    sa.Column('pillar_balance', sa.Float(), nullable=False),
    sa.Column('overall_trajectory', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.Column('cycle_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['gs_weekly_cycle.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gs_weekly_fitness_plan',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('cycle_id', sa.Uuid(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('target_sessions', sa.Integer(), nullable=False),
    sa.Column('domain_allocation', sa.JSON(), nullable=False),
    sa.Column('selected_exercises', sa.JSON(), nullable=False),
    sa.Column('session_outlines', sa.JSON(), nullable=True),
    sa.Column('stress_budget', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('fitness_engine_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('exercise_library_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('completed_sessions', sa.Integer(), nullable=False),
    sa.Column('adherence_met', sa.Boolean(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['gs_weekly_cycle.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gs_weekly_review',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cycle_id', sa.Uuid(), nullable=False),
    sa.Column('goals_met', sa.Integer(), nullable=False),
    sa.Column('goals_missed', sa.Integer(), nullable=False),
    sa.Column('goals_adjusted', sa.Integer(), nullable=False),
    sa.Column('qualitative_reflection', sa.Text(), nullable=True),
    sa.Column('reflection_energy_level', sa.Float(), nullable=True),
    sa.Column('reflection_motivation', sa.Float(), nullable=True),
    sa.Column('reflection_perceived_control', sa.Float(), nullable=True),
    sa.Column('adjustments_made', sa.JSON(), nullable=True),
    sa.Column('self_concept_delta', sa.JSON(), nullable=True),
    sa.Column('cognition_session_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['gs_weekly_cycle.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cycle_id')
    )
    op.create_table('gs_fitness_session_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('perceived_effort', sa.Float(), nullable=True),
    sa.Column('energy_level', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('actual_exercises', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['gs_weekly_fitness_plan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gs_fitness_state',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('training_age_weeks', sa.Integer(), nullable=False),
    sa.Column('endurance_level', sa.Float(), nullable=False),
    sa.Column('skeletal_muscular_level', sa.Float(), nullable=False),
    sa.Column('mobility_level', sa.Float(), nullable=False),
    sa.Column('self_efficacy', sa.Float(), nullable=False),
    sa.Column('adherence_score', sa.Float(), nullable=False),
    sa.Column('fitness_engine_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('exercise_library_version', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('last_plan_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['last_plan_id'], ['gs_weekly_fitness_plan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('gs_goal_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('goal_cycle_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('intensity_actual', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['goal_cycle_id'], ['gs_goal_cycle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gs_habit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('habit_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('intensity_actual', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['gs_habit.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gs_pillar_assessment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pillar_id', sa.Uuid(), nullable=False),
    sa.Column('assessed_at', sa.DateTime(), nullable=False),
    sa.Column('level', sa.Float(), nullable=False),
    sa.Column('sub_axes_snapshot', sa.JSON(), nullable=False),
    sa.Column('source', sa.Enum('SELF_REPORT', 'GOAL_ADHERENCE', 'COGNITION_INFERENCE', name='assessmentsource'), nullable=False),
    sa.ForeignKeyConstraint(['pillar_id'], ['gs_health_pillar.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gs_pillar_assessment')
    op.drop_table('gs_habit_log')
    op.drop_table('gs_goal_log')
    op.drop_table('gs_fitness_state')
    op.drop_table('gs_fitness_session_log')
    op.drop_table('gs_weekly_review')
    op.drop_table('gs_weekly_fitness_plan')
    op.drop_table('gs_trajectory_vector')
    op.drop_table('gs_stability_score')
    op.drop_table('gs_self_concept_snapshot')
    op.drop_table('gs_metric_data_point')
    op.drop_table('gs_meal_entry')
    op.drop_table('gs_identity_consistency_index')
    op.drop_table('gs_health_pillar')
    op.drop_table('gs_habit')
    op.drop_table('gs_goal_cycle')
    op.drop_table('gs_weekly_cycle')
    op.drop_table('gs_user_resource_profile')
    op.drop_table('gs_qualitative_observation')
    op.drop_table('gs_nutrition_log')
    op.drop_index(op.f('ix_gs_metric_time_series_metric_name'), table_name='gs_metric_time_series')
    op.drop_table('gs_metric_time_series')
    op.drop_table('gs_meal_plan')
    op.drop_table('gs_health_profile')
    op.drop_table('gs_goal')
    op.drop_table('gs_escalation_signal')
    op.drop_table('gs_concept_dimension')
    op.drop_index(op.f('ix_goal_scaffold_event_processed'), table_name='goal_scaffold_event')
    op.drop_index(op.f('ix_goal_scaffold_event_event_type'), table_name='goal_scaffold_event')
    op.drop_index(op.f('ix_goal_scaffold_event_emitted_at'), table_name='goal_scaffold_event')
    op.drop_index(op.f('ix_goal_scaffold_event_domain'), table_name='goal_scaffold_event')
    op.drop_table('goal_scaffold_event')
    op.drop_index(op.f('ix_gs_exercise_definition_name'), table_name='gs_exercise_definition')
    op.drop_index(op.f('ix_gs_exercise_definition_library_version'), table_name='gs_exercise_definition')
    op.drop_table('gs_exercise_definition')
    # ### end Alembic commands ###
