"""add_custom_numeric_scale_fields

Revision ID: 6bce073103ce
Revises: e3f102a658cd
Create Date: 2026-01-27 00:34:44.605764

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6bce073103ce'
down_revision = 'e3f102a658cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new enum value to scaletype
    op.execute("ALTER TYPE scaletype ADD VALUE IF NOT EXISTS 'CUSTOM_NUMERIC'")
    
    op.add_column('question', sa.Column('custom_min_value', sa.Integer(), nullable=True))
    op.add_column('question', sa.Column('custom_max_value', sa.Integer(), nullable=True))
    op.add_column('question', sa.Column('custom_unit_label', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'custom_unit_label')
    op.drop_column('question', 'custom_max_value')
    op.drop_column('question', 'custom_min_value')
    # ### end Alembic commands ###
