"""add_question_sections

Revision ID: ea0ea4bbd5b4
Revises: 258ee14f025b
Create Date: 2026-03-28 11:01:00.565832

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ea0ea4bbd5b4'
down_revision = '783d162ef1f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionsection',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('questionnaire_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['questionnaire_id'], ['questionnairetemplate.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('question', sa.Column('section_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'question', 'questionsection', ['section_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('question_section_id_fkey', 'question', type_='foreignkey')
    op.drop_column('question', 'section_id')
    op.drop_table('questionsection')
    # ### end Alembic commands ###
