/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as RecoverPasswordImport } from './routes/recover-password'
import { Route as LoginImport } from './routes/login'
import { Route as BesciDemoImport } from './routes/besci-demo'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutValueMapImport } from './routes/_layout/value-map'
import { Route as LayoutSettingsImport } from './routes/_layout/settings'
import { Route as LayoutCheckinsImport } from './routes/_layout/checkins'
import { Route as LayoutChatImport } from './routes/_layout/chat'
import { Route as LayoutAdminImport } from './routes/_layout/admin'
import { Route as LayoutQuestionnairesIndexImport } from './routes/_layout/questionnaires.index'
import { Route as LayoutAdminQuestionnairesImport } from './routes/_layout/admin.questionnaires'
import { Route as LayoutQuestionnairesAssignmentIdTakeImport } from './routes/_layout/questionnaires/$assignmentId.take'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const RecoverPasswordRoute = RecoverPasswordImport.update({
  path: '/recover-password',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const BesciDemoRoute = BesciDemoImport.update({
  path: '/besci-demo',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutValueMapRoute = LayoutValueMapImport.update({
  path: '/value-map',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSettingsRoute = LayoutSettingsImport.update({
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutCheckinsRoute = LayoutCheckinsImport.update({
  path: '/checkins',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutChatRoute = LayoutChatImport.update({
  path: '/chat',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminRoute = LayoutAdminImport.update({
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutQuestionnairesIndexRoute = LayoutQuestionnairesIndexImport.update({
  path: '/questionnaires/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminQuestionnairesRoute = LayoutAdminQuestionnairesImport.update({
  path: '/questionnaires',
  getParentRoute: () => LayoutAdminRoute,
} as any)

const LayoutQuestionnairesAssignmentIdTakeRoute =
  LayoutQuestionnairesAssignmentIdTakeImport.update({
    path: '/questionnaires/$assignmentId/take',
    getParentRoute: () => LayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/besci-demo': {
      preLoaderRoute: typeof BesciDemoImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/recover-password': {
      preLoaderRoute: typeof RecoverPasswordImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_layout/admin': {
      preLoaderRoute: typeof LayoutAdminImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/chat': {
      preLoaderRoute: typeof LayoutChatImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/checkins': {
      preLoaderRoute: typeof LayoutCheckinsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings': {
      preLoaderRoute: typeof LayoutSettingsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/value-map': {
      preLoaderRoute: typeof LayoutValueMapImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/admin/questionnaires': {
      preLoaderRoute: typeof LayoutAdminQuestionnairesImport
      parentRoute: typeof LayoutAdminImport
    }
    '/_layout/questionnaires/': {
      preLoaderRoute: typeof LayoutQuestionnairesIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/questionnaires/$assignmentId/take': {
      preLoaderRoute: typeof LayoutQuestionnairesAssignmentIdTakeImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutAdminRoute.addChildren([LayoutAdminQuestionnairesRoute]),
    LayoutChatRoute,
    LayoutCheckinsRoute,
    LayoutSettingsRoute,
    LayoutValueMapRoute,
    LayoutIndexRoute,
    LayoutQuestionnairesIndexRoute,
    LayoutQuestionnairesAssignmentIdTakeRoute,
  ]),
  BesciDemoRoute,
  LoginRoute,
  RecoverPasswordRoute,
  ResetPasswordRoute,
  SignupRoute,
])

/* prettier-ignore-end */
