from __future__ import annotations

from dataclasses import dataclass, field


@dataclass(frozen=True)
class ConstructDefinition:
    name: str
    rationale: str
    positive_words: set[str] = field(default_factory=set)
    negative_words: set[str] = field(default_factory=set)
    positive_phrases: set[str] = field(default_factory=set)
    negative_phrases: set[str] = field(default_factory=set)
    positive_anchors: list[str] = field(default_factory=list)
    negative_anchors: list[str] = field(default_factory=list)


BASE_DIMENSIONS: dict[str, ConstructDefinition] = {
    "valence": ConstructDefinition(
        name="valence",
        rationale="Tracks whether language trends toward distress, emptiness, and hopelessness versus relief, hope, and positive tone.",
        positive_words={
            "better",
            "calm",
            "clear",
            "connected",
            "content",
            "encouraged",
            "good",
            "grateful",
            "great",
            "grounded",
            "happy",
            "hopeful",
            "joy",
            "lighter",
            "motivated",
            "okay",
            "optimistic",
            "proud",
            "relieved",
            "safe",
            "steadier",
            "supported",
            "warm",
        },
        negative_words={
            "alone",
            "angry",
            "bad",
            "depressed",
            "drained",
            "empty",
            "flat",
            "guilty",
            "heavy",
            "hopeless",
            "irritable",
            "isolated",
            "lonely",
            "low",
            "miserable",
            "numb",
            "sad",
            "shame",
            "stuck",
            "terrible",
            "tough",
            "upset",
            "worthless",
        },
        positive_phrases={"feel more like myself", "felt supported and connected"},
        negative_phrases={
            "too much effort",
            "going through the motions",
            "go through the motions",
            "did not have the energy",
            "didn't have the energy",
            "not getting done",
        },
        positive_anchors=[
            "feeling hopeful grounded supported and emotionally better",
            "connected optimistic relieved and doing okay",
        ],
        negative_anchors=[
            "feeling empty hopeless numb isolated and bad",
            "stuck drained lonely and emotionally low",
        ],
    ),
    "arousal": ConstructDefinition(
        name="arousal",
        rationale="Tracks activated, threatened, agitated language versus settled, regulated, and calmer language.",
        positive_words={
            "afraid",
            "agitated",
            "anxious",
            "chaotic",
            "frantic",
            "hyper",
            "nervous",
            "overwhelmed",
            "panic",
            "pressured",
            "restless",
            "rushed",
            "scared",
            "shaken",
            "spiraling",
            "stressed",
            "tense",
            "urgent",
            "wired",
        },
        negative_words={
            "calm",
            "centered",
            "easier",
            "grounded",
            "peaceful",
            "settled",
            "steady",
            "still",
        },
        positive_anchors=[
            "feeling anxious overwhelmed pressured agitated and wired",
            "frantic tense stressed and restless",
        ],
        negative_anchors=[
            "feeling calm settled grounded steady and peaceful",
            "still centered and easier in my body",
        ],
    ),
    "control": ConstructDefinition(
        name="control",
        rationale="Tracks planning, follow-through, and self-regulation versus scattered, reactive, and dysregulated language.",
        positive_words={
            "able",
            "committed",
            "decided",
            "discipline",
            "focus",
            "focused",
            "followed",
            "handle",
            "managed",
            "organized",
            "plan",
            "planned",
            "practice",
            "regulated",
            "routine",
            "stable",
            "stayed",
            "through",
        },
        negative_words={
            "avoid",
            "avoided",
            "compulsive",
            "derailed",
            "ignored",
            "impulsive",
            "lost",
            "reactive",
            "scattered",
            "spiraled",
            "stuck",
            "unable",
            "uncontrolled",
        },
        positive_phrases={"made a plan", "followed through", "followed through on"},
        negative_phrases={"could not focus", "couldn't focus"},
        positive_anchors=[
            "made a plan stayed organized followed through and handled things",
            "focused managed routine and self regulation",
        ],
        negative_anchors=[
            "felt impulsive scattered unable to focus and derailed",
            "reactive lost control and spiraling",
        ],
    ),
    "social_orientation": ConstructDefinition(
        name="social_orientation",
        rationale="Tracks connection, sharedness, and support versus isolation, detachment, and withdrawal.",
        positive_words={
            "connected",
            "connection",
            "family",
            "friend",
            "friends",
            "group",
            "partner",
            "people",
            "shared",
            "supportive",
            "supported",
            "team",
            "together",
            "we",
            "with",
        },
        negative_words={
            "alone",
            "detached",
            "disconnected",
            "ignored",
            "isolated",
            "nobody",
            "avoid",
            "avoided",
            "withdraw",
            "withdrew",
            "withdrawn",
        },
        positive_phrases={"spent time with friends", "felt supported and connected"},
        negative_phrases={"stayed home", "ignored a message", "felt isolated", "avoided people"},
        positive_anchors=[
            "spent time with friends felt supported and socially connected",
            "shared with people and felt together with others",
        ],
        negative_anchors=[
            "withdrew avoided people felt detached and isolated",
            "stayed home ignored messages and disconnected from everyone",
        ],
    ),
    "reward_seeking": ConstructDefinition(
        name="reward_seeking",
        rationale="Tracks curiosity, interest, and approach motivation versus flatness, low reward, and effortful disengagement.",
        positive_words={
            "achievement",
            "curious",
            "enjoy",
            "enjoyable",
            "enjoyed",
            "fun",
            "interested",
            "motivated",
            "pleasure",
            "progress",
            "rewarding",
            "want",
        },
        negative_words={
            "anhedonia",
            "blank",
            "effort",
            "empty",
            "flat",
            "motions",
            "numb",
            "pointless",
            "tired",
            "unmotivated",
        },
        positive_phrases={"felt curious", "enjoyed the walk"},
        negative_phrases={
            "nothing feels enjoyable",
            "nothing sounds especially rewarding",
            "nothing sounded rewarding",
            "did not sound rewarding",
            "didn't sound rewarding",
            "going through the motions",
            "go through the motions",
            "too much effort",
        },
        positive_anchors=[
            "felt curious interested engaged and enjoyed things again",
            "motivated rewarding pleasurable and wanting to participate",
        ],
        negative_anchors=[
            "flat numb nothing enjoyable and too much effort",
            "pointless unmotivated and going through the motions",
        ],
    ),
    "cognitive_flexibility": ConstructDefinition(
        name="cognitive_flexibility",
        rationale="Tracks adaptation, reframing, and experimentation versus rigid, absolutist, and trapped language.",
        positive_words={
            "adapt",
            "adjust",
            "adjusted",
            "alternate",
            "balance",
            "curious",
            "experiment",
            "flexible",
            "learn",
            "option",
            "reframe",
            "reframed",
            "shift",
            "try",
        },
        negative_words={
            "always",
            "impossible",
            "must",
            "never",
            "nothing",
            "rigid",
            "ruined",
            "should",
            "totally",
            "trapped",
        },
        positive_phrases={"alternate approach", "keep trying"},
        negative_phrases={"nothing could change"},
        positive_anchors=[
            "adjusted reframed and tried an alternate approach",
            "adapted learned shifted and kept trying",
        ],
        negative_anchors=[
            "felt trapped rigid and like nothing could change",
            "must always never impossible and totally stuck",
        ],
    ),
}


PROCESS_CONSTRUCTS: dict[str, ConstructDefinition] = {
    "threat_sensitivity": ConstructDefinition(
        name="threat_sensitivity",
        rationale="Captures threat-focused, vigilance-heavy language versus safety and embodied ease.",
        positive_words={
            "afraid",
            "alarm",
            "anxious",
            "catastrophic",
            "danger",
            "fear",
            "hypervigilant",
            "nervous",
            "panic",
            "scared",
            "tense",
            "threat",
            "unsafe",
            "vigilant",
            "worried",
        },
        negative_words={"calm", "eased", "grounded", "protected", "safe", "secure", "settled", "steady"},
        positive_phrases={"on edge", "bracing for", "waiting for something bad"},
        negative_phrases={"felt safe enough", "could let my guard down"},
        positive_anchors=[
            "on edge scanning for danger and expecting something bad",
            "threat focused fearful vigilant and unsafe",
        ],
        negative_anchors=[
            "safe grounded settled and not bracing for danger",
            "secure and able to let my guard down",
        ],
    ),
    "perseverative_cognition": ConstructDefinition(
        name="perseverative_cognition",
        rationale="Captures rumination, looping, and stuck thought patterns versus release, reframing, and mental movement.",
        positive_words={
            "always",
            "can't",
            "cannot",
            "looping",
            "obsessing",
            "overthinking",
            "ruminating",
            "spiraling",
            "stuck",
            "trapped",
            "unending",
            "won't",
        },
        negative_words={"accepted", "adjusted", "breathed", "let", "noticed", "reframed", "released", "shifted"},
        positive_phrases={"keep thinking about", "could not stop thinking", "same thoughts again"},
        negative_phrases={"let it pass", "shifted my perspective"},
        positive_anchors=[
            "kept looping on the same thoughts and could not let go",
            "ruminating spiraling and mentally trapped",
        ],
        negative_anchors=[
            "noticed the thought and let it pass",
            "reframed and mentally shifted without looping",
        ],
    ),
    "behavioral_activation": ConstructDefinition(
        name="behavioral_activation",
        rationale="Captures approach, initiative, and doing versus shutdown, inertia, and depletion.",
        positive_words={
            "active",
            "did",
            "engaged",
            "moved",
            "participated",
            "practice",
            "progress",
            "reached",
            "started",
            "tried",
            "walked",
            "worked",
        },
        negative_words={"depleted", "effort", "frozen", "heavy", "inactive", "numb", "shut", "stalled", "stayed", "tired", "unable"},
        positive_phrases={"took a step", "reached out", "showed up"},
        negative_phrases={"couldn't get myself", "stayed in bed", "too exhausted to"},
        positive_anchors=[
            "took action showed up and kept moving even if it was small",
            "initiated participated and engaged with life",
        ],
        negative_anchors=[
            "shut down unable to act and too exhausted to move",
            "stalled depleted and behaviorally frozen",
        ],
    ),
    "social_avoidance": ConstructDefinition(
        name="social_avoidance",
        rationale="Captures hiding, withdrawing, and avoiding contact versus approach, reaching out, and staying in contact.",
        positive_words={"avoid", "avoided", "cancelled", "hid", "ignored", "isolated", "retreated", "withdrew", "withdrawn"},
        negative_words={"called", "connected", "messaged", "met", "reached", "responded", "shared", "talked", "visited"},
        positive_phrases={"did not answer", "ignored a message", "stayed away from people"},
        negative_phrases={"reached out to", "spent time with", "answered one message"},
        positive_anchors=[
            "avoided contact hid from people and pulled away socially",
            "withdrew ignored messages and stayed away from others",
        ],
        negative_anchors=[
            "reached out responded and stayed connected to people",
            "engaged socially and did not hide from others",
        ],
    ),
    "relational_ambivalence": ConstructDefinition(
        name="relational_ambivalence",
        rationale="Captures intimacy or relationship movement that feels misaligned, unwanted, confusing, or farther than intended.",
        positive_words={
            "ambivalent",
            "conflicted",
            "hookup",
            "intimate",
            "sex",
            "sexual",
            "unsure",
            "women",
            "woman",
            "men",
            "man",
        },
        negative_words={
            "clear",
            "direct",
            "intentional",
            "wanted",
            "aligned",
            "mutual",
        },
        positive_phrases={
            "farther than i would like",
            "further than i would like",
            "more than i wanted",
            "more intimate than i wanted",
            "closer than i wanted",
            "didn't really want",
            "did not really want",
            "not what i wanted",
            "ended up with",
            "got into something i didn't want",
        },
        negative_phrases={
            "this is what i want",
            "felt aligned with what i wanted",
            "clear about my boundaries",
            "clear about what i wanted",
        },
        positive_anchors=[
            "kept getting into intimacy or relationship situations that went farther than wanted",
            "confused mixed signals and relational movement that felt misaligned with desire",
        ],
        negative_anchors=[
            "clear intentional and aligned about intimacy and relationship boundaries",
            "mutual and wanted connection with direct relational agency",
        ],
    ),
    "somatic_burden": ConstructDefinition(
        name="somatic_burden",
        rationale="Captures fatigue, heaviness, and bodily depletion versus energy, lightness, and physical ease.",
        positive_words={"drained", "exhausted", "fatigued", "foggy", "heavy", "numb", "sluggish", "tired", "wiped"},
        negative_words={"awake", "clear", "energized", "light", "rested", "restored", "steady"},
        positive_phrases={"no energy", "too tired to", "body felt heavy"},
        negative_phrases={"had more energy", "body felt lighter"},
        positive_anchors=[
            "body felt heavy drained and depleted",
            "exhausted fatigued and physically shut down",
        ],
        negative_anchors=[
            "rested lighter energized and physically steadier",
            "body felt clearer and less burdened",
        ],
    ),
    "absolutist_thinking": ConstructDefinition(
        name="absolutist_thinking",
        rationale="Captures all-or-nothing, totalizing, and no-way-out language that often sharpens distress and reduces nuance.",
        positive_words={
            "always",
            "completely",
            "entirely",
            "everyone",
            "everything",
            "impossible",
            "never",
            "nothing",
            "totally",
        },
        negative_words={"maybe", "partly", "sometimes", "somewhat"},
        positive_phrases={
            "no way out",
            "nothing will change",
            "everything is ruined",
            "always happens",
        },
        negative_phrases={"this is only part of it", "there may be another way"},
        positive_anchors=[
            "using all or nothing language with no nuance or room for exception",
            "everything feels total final impossible and absolute",
        ],
        negative_anchors=[
            "holding nuance partiality and room for alternative explanations",
            "not treating the moment as total or final",
        ],
    ),
    "social_evaluative_concern": ConstructDefinition(
        name="social_evaluative_concern",
        rationale="Captures monitoring of how one is coming across, fear of judgment, embarrassment, rejection, and interpersonal performance pressure.",
        positive_words={
            "awkward",
            "embarrassed",
            "judged",
            "rejected",
            "selfconscious",
            "watched",
        },
        negative_words={"accepted", "comfortable", "safe", "unselfconscious"},
        positive_phrases={
            "what they think of me",
            "how i came across",
            "looked stupid",
            "felt judged",
        },
        negative_phrases={
            "did not feel judged",
            "felt socially safe",
            "was not performing for them",
        },
        positive_anchors=[
            "tracking judgment embarrassment rejection and interpersonal performance closely",
            "social situations feel evaluative exposing and hard to relax in",
        ],
        negative_anchors=[
            "socially safe enough to not overmonitor how i am coming across",
            "less preoccupied with evaluation or rejection",
        ],
    ),
    "self_criticism": ConstructDefinition(
        name="self_criticism",
        rationale="Captures harsh negative self-evaluation, defectiveness, shame, and self-blame versus self-acceptance or balanced appraisal.",
        positive_words={
            "ashamed",
            "broken",
            "defective",
            "failure",
            "fault",
            "guilty",
            "pathetic",
            "stupid",
            "useless",
            "worthless",
        },
        negative_words={"forgave", "gentle", "okay", "patient", "worthy"},
        positive_phrases={
            "something is wrong with me",
            "i am the problem",
            "i hate myself",
        },
        negative_phrases={
            "i can be gentler with myself",
            "this does not define me",
        },
        positive_anchors=[
            "harsh self blame shame and defectiveness are central",
            "talking to myself as though i am fundamentally bad or failing",
        ],
        negative_anchors=[
            "self appraisal is gentler more balanced and less condemning",
            "not collapsing into shame or defectiveness",
        ],
    ),
    "approach_bias": ConstructDefinition(
        name="approach_bias",
        rationale="Captures moving toward goals, people, and rewards versus not orienting toward engagement.",
        positive_words={
            "approach",
            "leaned",
            "moved",
            "pursued",
            "reached",
            "showed",
            "toward",
            "went",
        },
        negative_words={"backed", "hid", "retreated", "stayed"},
        positive_phrases={"moved toward", "leaned into", "went after"},
        negative_phrases={"backed away from", "pulled back from"},
        positive_anchors=[
            "oriented toward people goals and potentially rewarding experiences",
            "moving toward engagement instead of shrinking back",
        ],
        negative_anchors=[
            "not moving toward rewarding or social opportunities",
            "failing to orient toward engagement or action",
        ],
    ),
    "avoidance_bias": ConstructDefinition(
        name="avoidance_bias",
        rationale="Captures pulling back, hiding, and orienting away from challenge, contact, or discomfort.",
        positive_words={
            "avoid",
            "backed",
            "dodged",
            "escaped",
            "hid",
            "retreated",
            "withdrew",
        },
        negative_words={"approached", "faced", "met", "showed"},
        positive_phrases={"pulled away", "pulled back", "stayed away", "backed off"},
        negative_phrases={"faced it", "met it directly"},
        positive_anchors=[
            "orienting away from discomfort challenge or contact",
            "behavior is organized around backing off hiding or escape",
        ],
        negative_anchors=[
            "moving toward discomfort or challenge rather than escaping it",
            "not organized around avoidance or retreat",
        ],
    ),
    "boundary_diffusion": ConstructDefinition(
        name="boundary_diffusion",
        rationale="Captures porous, unclear, or overrun interpersonal boundaries versus clear relational limits and agency.",
        positive_words={
            "blurred",
            "enmeshed",
            "overrun",
            "porous",
            "swept",
        },
        negative_words={"clear", "defined", "firm", "protected"},
        positive_phrases={
            "farther than i wanted",
            "could not hold my boundary",
            "went along with it",
            "hard to say no",
            "lost my boundary",
        },
        negative_phrases={
            "held my boundary",
            "was clear about my limit",
            "knew where i stood",
        },
        positive_anchors=[
            "boundaries feel porous overrun or hard to maintain in relationships",
            "going along with relational momentum that does not feel fully chosen",
        ],
        negative_anchors=[
            "clear interpersonal limits with intact relational agency",
            "able to hold boundaries and choose relational distance intentionally",
        ],
    ),
    "negative_audience_effect": ConstructDefinition(
        name="negative_audience_effect",
        rationale="Captures situations where the presence, choices, or judgment of others seems to impair performance, learning, or reward.",
        positive_words={
            "watched",
            "pressure",
        },
        negative_words={"unbothered", "unfazed"},
        positive_phrases={
            "did worse when people were around",
            "their presence threw me off",
            "could not focus because they were there",
            "performed worse around them",
            "their choices got in my head",
        },
        negative_phrases={
            "other people did not throw me off",
            "their presence did not change my focus",
        },
        positive_anchors=[
            "social context or audience effects interfere with reward learning or performance",
            "the presence or choices of others make me do worse or lose my footing",
        ],
        negative_anchors=[
            "social context does not meaningfully disrupt performance or reward pursuit",
            "able to stay oriented even when others are present or watching",
        ],
    ),
    "uncertain_threat_anticipation": ConstructDefinition(
        name="uncertain_threat_anticipation",
        rationale="Captures mounting apprehension when something bad might happen but timing or certainty is unclear.",
        positive_words={
            "anticipating",
            "bracing",
            "dread",
            "looming",
            "waiting",
        },
        negative_words={"predictable", "resolved", "settled"},
        positive_phrases={
            "waiting for the other shoe to drop",
            "something bad could happen any time",
            "waiting for it to happen",
            "dreading what might come",
        },
        negative_phrases={
            "the uncertainty settled",
            "i knew what to expect",
        },
        positive_anchors=[
            "uncertain threat grows in anticipation and drives anxiety before anything happens",
            "the not knowing itself is generating fear and avoidance",
        ],
        negative_anchors=[
            "threat is resolved or predictable enough not to drive mounting apprehension",
            "not living in prolonged anticipation of uncertain danger",
        ],
    ),
    "agency_awareness": ConstructDefinition(
        name="agency_awareness",
        rationale="Captures reflective awareness joined with a sense of authorship, choice, and capacity to respond intentionally.",
        positive_words={
            "aware",
            "chose",
            "choice",
            "noticed",
            "owned",
            "responded",
        },
        negative_words={"automatic", "helpless", "swept", "unaware"},
        positive_phrases={
            "noticed and chose",
            "caught myself and redirected",
            "i could choose my response",
        },
        negative_phrases={
            "it just took over",
            "i was on autopilot",
            "had no say in it",
        },
        positive_anchors=[
            "awareness is translating into agency choice and intentional response",
            "able to observe internal state and act with some authorship",
        ],
        negative_anchors=[
            "automaticity or helplessness is overriding reflective agency",
            "awareness is low or not translating into intentional action",
        ],
    ),
    "imagery_density": ConstructDefinition(
        name="imagery_density",
        rationale="Captures how strongly the writing relies on concrete images, objects, places, and scene-building rather than only abstract report language.",
        positive_words={
            "ash",
            "bed",
            "blood",
            "bone",
            "chair",
            "clock",
            "door",
            "dust",
            "face",
            "floor",
            "glass",
            "hallway",
            "hand",
            "house",
            "knife",
            "light",
            "mirror",
            "night",
            "rain",
            "room",
            "shadow",
            "skin",
            "smoke",
            "stone",
            "street",
            "sun",
            "wall",
            "water",
            "window",
        },
        negative_words={"issue", "pattern", "process", "situation", "thing"},
        positive_phrases={
            "in the room",
            "on the floor",
            "in my hands",
            "through the window",
        },
        negative_phrases={"it was hard to explain", "the general situation"},
        positive_anchors=[
            "the feeling is carried by vivid concrete images objects places and scenes",
            "emotion is being rendered through sensory details and visual material",
        ],
        negative_anchors=[
            "the writing stays generic abstract and low in image making",
            "little concrete scene building or object level imagery is present",
        ],
    ),
    "sensory_grounding": ConstructDefinition(
        name="sensory_grounding",
        rationale="Captures embodied, sensory, and felt-detail language rather than purely conceptual or disembodied description.",
        positive_words={
            "bitter",
            "bright",
            "cold",
            "dark",
            "echo",
            "heavy",
            "hot",
            "loud",
            "metallic",
            "quiet",
            "rough",
            "salt",
            "sharp",
            "silent",
            "smell",
            "soft",
            "sound",
            "stiff",
            "taste",
            "tight",
            "warm",
        },
        negative_words={"conceptual", "detached", "disembodied", "intellectualized"},
        positive_phrases={
            "felt it in my body",
            "could taste it",
            "sounded like",
            "smelled like",
        },
        negative_phrases={"hard to feel", "just an idea"},
        positive_anchors=[
            "the language is sensory embodied and grounded in felt experience",
            "emotion is expressed through bodily and sensory detail",
        ],
        negative_anchors=[
            "the writing is disembodied abstract and low in sensory contact",
            "experience is described conceptually rather than through felt detail",
        ],
    ),
    "affective_explicitness": ConstructDefinition(
        name="affective_explicitness",
        rationale="Captures direct naming of feelings and emotion states rather than only circling them indirectly.",
        positive_words={
            "afraid",
            "angry",
            "ashamed",
            "calm",
            "depressed",
            "happy",
            "hurt",
            "joy",
            "lonely",
            "love",
            "panic",
            "relieved",
            "sad",
            "scared",
            "upset",
        },
        negative_words={"indirect", "veiled"},
        positive_phrases={
            "i feel",
            "i felt",
            "made me feel",
            "it left me feeling",
        },
        negative_phrases={"hard to name", "could not name it"},
        positive_anchors=[
            "the emotion is named directly rather than only implied",
            "feeling words are being used explicitly and plainly",
        ],
        negative_anchors=[
            "emotion is not being named directly and stays largely implied",
            "affect is present but not directly labeled in the language",
        ],
    ),
    "affective_implication": ConstructDefinition(
        name="affective_implication",
        rationale="Captures emotional meaning that is suggested through imagery, metaphor, and symbolic phrasing rather than stated outright.",
        positive_words={
            "echo",
            "ghost",
            "hollow",
            "shadow",
            "storm",
            "undertow",
            "weight",
        },
        negative_words={"clear", "literal", "plain", "stated"},
        positive_phrases={
            "as if",
            "as though",
            "felt like",
            "like a",
            "like the",
            "the room felt",
            "the day felt",
        },
        negative_phrases={"to be clear", "plainly put", "directly said"},
        positive_anchors=[
            "emotion is implied through imagery metaphor or symbolic comparison",
            "the writing suggests feeling indirectly instead of naming it outright",
        ],
        negative_anchors=[
            "emotion is described literally and explicitly rather than through symbolic language",
            "the language stays direct matter of fact and low in metaphorical implication",
        ],
    ),
    "abstract_reflection": ConstructDefinition(
        name="abstract_reflection",
        rationale="Captures reflective, symbolic, and conceptual language that stands back from immediate events to think about meaning, identity, and interpretation.",
        positive_words={
            "absence",
            "identity",
            "meaning",
            "memory",
            "narrative",
            "pattern",
            "presence",
            "self",
            "story",
            "symbol",
            "theme",
            "version",
            "void",
        },
        negative_words={"literal", "practical", "specific"},
        positive_phrases={
            "it meant",
            "the pattern was",
            "a part of me",
            "the kind of person",
        },
        negative_phrases={"the concrete task", "the specific step"},
        positive_anchors=[
            "the writing leans reflective symbolic and abstract rather than only event literal",
            "meaning identity and interpretation are foregrounded in the language",
        ],
        negative_anchors=[
            "the writing stays immediate concrete and low in abstract reflection",
            "little symbolic or conceptual distance is being taken from the event",
        ],
    ),
}


COMPUTATIONAL_CONSTRUCTS: dict[str, ConstructDefinition] = {
    "dopaminergic_pressure": ConstructDefinition(
        name="dopaminergic_pressure",
        rationale="Approximates reward drive, incentive salience, and action vigor from language about wanting, pursuing, and feeling rewardable momentum versus flatness and no-spark states.",
        positive_words={
            "drive",
            "driven",
            "eager",
            "energized",
            "excited",
            "momentum",
            "pursue",
            "spark",
            "striving",
            "vital",
            "wanting",
        },
        negative_words={
            "anhedonia",
            "blank",
            "flat",
            "listless",
            "numb",
            "pointless",
            "stale",
            "unmoved",
        },
        positive_phrases={"felt pulled toward", "wanted to go after", "had some spark again"},
        negative_phrases={"no spark", "nothing pulled me", "could not want anything"},
        positive_anchors=[
            "feeling reward pulled energized wanting things and able to pursue them",
            "momentum spark incentive and action vigor are present",
        ],
        negative_anchors=[
            "flat unrewarding no spark and nothing feels worth pursuing",
            "blunted drive with little wanting or incentive salience",
        ],
    ),
    "control_allocation": ConstructDefinition(
        name="control_allocation",
        rationale="Approximates whether a person seems able to invest effortful control where it matters, versus being unable to marshal sustained regulation.",
        positive_words={
            "committed",
            "disciplined",
            "focused",
            "prioritized",
            "protected",
            "regulated",
            "sustained",
        },
        negative_words={
            "distracted",
            "drained",
            "fragmented",
            "scattered",
            "spent",
            "unable",
            "unfocused",
        },
        positive_phrases={
            "put my effort where it mattered",
            "held the line",
            "stayed on the plan",
        },
        negative_phrases={
            "could not make myself",
            "spent all my energy reacting",
            "kept losing the thread",
        },
        positive_anchors=[
            "able to allocate control stay focused and sustain effort where needed",
            "organized regulation with effort placed intentionally",
        ],
        negative_anchors=[
            "unable to marshal control scattered and losing effort to reactivity",
            "control resources feel depleted fragmented and poorly allocated",
        ],
    ),
    "volatility_expectancy": ConstructDefinition(
        name="volatility_expectancy",
        rationale="Approximates whether the person sounds like they expect instability, rapid shifts, or unpredictable outcomes versus predictability and steadiness.",
        positive_words={
            "fragile",
            "shaky",
            "sudden",
            "swinging",
            "uncertain",
            "unstable",
            "unsteady",
        },
        negative_words={
            "anchored",
            "predictable",
            "reliable",
            "steady",
            "stable",
        },
        positive_phrases={"could turn at any second", "waiting for the other shoe to drop"},
        negative_phrases={"felt predictable enough", "things stayed steady"},
        positive_anchors=[
            "expecting instability abrupt shifts and unpredictable outcomes",
            "living as if things could swing or collapse quickly",
        ],
        negative_anchors=[
            "expecting stability predictability and steady outcomes",
            "feeling anchored enough that things will hold",
        ],
    ),
    "prediction_error_weighting": ConstructDefinition(
        name="prediction_error_weighting",
        rationale="Approximates how strongly small cues or deviations seem to punch through the person's model of the world, versus being contextualized without overload.",
        positive_words={
            "fixated",
            "jolted",
            "overread",
            "overreacted",
            "read into",
            "sensitive",
            "thrown",
            "triggered",
        },
        negative_words={
            "absorbed",
            "contextualized",
            "integrated",
            "rolled",
            "stable",
        },
        positive_phrases={
            "every small thing hit me hard",
            "could not ignore it",
            "read too much into it",
        },
        negative_phrases={
            "took it in stride",
            "saw it for what it was",
            "did not let it throw me",
        },
        positive_anchors=[
            "small cues or surprises feel magnified and hard to contextualize",
            "deviations hit with high salience and shift my state quickly",
        ],
        negative_anchors=[
            "new cues are integrated without overload or magnification",
            "able to contextualize surprises without large state shifts",
        ],
    ),
    "social_salience": ConstructDefinition(
        name="social_salience",
        rationale="Approximates how strongly interpersonal attention, approval, rejection, attraction, and belonging seem to organize the moment.",
        positive_words={
            "approval",
            "attraction",
            "belonging",
            "chemistry",
            "noticed",
            "rejection",
            "seen",
            "validation",
            "wanted",
        },
        negative_words={
            "detached",
            "indifferent",
            "numb",
            "unmoved",
        },
        positive_phrases={
            "what they thought of me",
            "how i came across",
            "whether they wanted me",
        },
        negative_phrases={
            "did not really register socially",
            "felt socially flat",
        },
        positive_anchors=[
            "social attention approval rejection or chemistry carry strong weight",
            "interpersonal cues feel highly salient and organizing",
        ],
        negative_anchors=[
            "social cues feel muted flat or low priority",
            "little interpersonal pull or reactivity is present",
        ],
    ),
    "effort_cost_load": ConstructDefinition(
        name="effort_cost_load",
        rationale="Approximates whether action and self-regulation are being experienced as costly, uphill, and depleting versus comparatively light and easy to initiate.",
        positive_words={
            "draining",
            "effortful",
            "exhausting",
            "hard",
            "heavy",
            "uphill",
        },
        negative_words={
            "doable",
            "easy",
            "flowing",
            "light",
            "natural",
            "smooth",
        },
        positive_phrases={
            "too much effort",
            "everything felt uphill",
            "cost more than i had",
        },
        negative_phrases={
            "came naturally",
            "felt more doable",
            "did not cost as much",
        },
        positive_anchors=[
            "acting feels effortful uphill and metabolically costly",
            "control and movement feel expensive and depleting",
        ],
        negative_anchors=[
            "action feels comparatively doable light and not so costly",
            "movement and regulation do not feel especially effortful",
        ],
    ),
    "social_reward_coupling": ConstructDefinition(
        name="social_reward_coupling",
        rationale="Approximates how strongly reward, performance, or motivation appear tied to the presence, judgment, or choices of other people.",
        positive_words={"approval", "audience", "chemistry", "impress", "validation"},
        negative_words={"independent", "self-directed"},
        positive_phrases={
            "their presence changed everything",
            "how they saw me changed how it felt",
            "reward depended on them",
        },
        negative_phrases={
            "i could stay with my own goal",
            "other people did not set the value of it",
        },
        positive_anchors=[
            "social context strongly changes reward pursuit performance or motivation",
            "what other people think or do is tightly coupled to how rewarding things feel",
        ],
        negative_anchors=[
            "reward pursuit remains relatively stable even when other people are present",
            "social context is not strongly setting the value of the moment",
        ],
    ),
    "threat_hazard_expectancy": ConstructDefinition(
        name="threat_hazard_expectancy",
        rationale="Approximates the sense that as time passes under uncertainty, the chance of something bad happening feels as though it is rising.",
        positive_words={"countdown", "looming", "pending"},
        negative_words={"contained", "known"},
        positive_phrases={
            "the longer it went on the worse it felt",
            "as time passed it felt more likely",
            "waiting made it worse",
        },
        negative_phrases={
            "time did not make it feel more dangerous",
            "waiting did not escalate it",
        },
        positive_anchors=[
            "uncertainty is compounding into a rising sense of threat over time",
            "hazard feels like it grows the longer resolution is delayed",
        ],
        negative_anchors=[
            "uncertainty is not snowballing into a growing threat expectancy",
            "delay does not seem to amplify the sense of danger",
        ],
    ),
    "agency_coherence": ConstructDefinition(
        name="agency_coherence",
        rationale="Approximates whether awareness, boundaries, and intentional action are cohering into felt authorship.",
        positive_words={"centered", "intentional", "owned", "steady"},
        negative_words={"automatic", "fragmented", "powerless"},
        positive_phrases={
            "i knew what i was doing and why",
            "i could hold my line",
            "i chose how to respond",
        },
        negative_phrases={
            "i had no say",
            "i was swept along",
            "it did not feel like my choice",
        },
        positive_anchors=[
            "awareness boundaries and intentional choice are hanging together coherently",
            "felt authorship is present rather than fragmented",
        ],
        negative_anchors=[
            "authorship is fractured and responses feel automatic or imposed",
            "awareness is not consolidating into coherent agency",
        ],
    ),
}


SELF_FOCUS_WORDS = {"i", "i'd", "i'll", "i'm", "i've", "me", "mine", "my", "myself"}


HIGHER_ORDER_FACTOR_RATIONALES = {
    "negative_affectivity": "Aggregates negative tone, arousal, threat sensitivity, self-criticism, and absolutist style into a broad negative-affectivity dimension aligned with dimensional psychopathology models.",
    "internalizing_distress": "Aggregates negative tone, low reward, lower agency, and self-focused perseveration into a broad distress-like dimension.",
    "internalizing_fear": "Aggregates arousal, volatility, threat sensitivity, and lower control into a fear/anxiety-like dimension.",
    "detachment": "Aggregates social withdrawal, low reward, flatter tone, and social avoidance into a detachment-like dimension.",
    "disinhibition": "Aggregates higher arousal, volatility, and lower control into a dysregulation/disinhibition-like dimension.",
    "social_anxious_attachment": "Aggregates social salience, social evaluative concern, relational ambivalence, and lower social ease into an interpersonal hyper-monitoring dimension.",
    "compulsive_rigidity": "Aggregates perseveration, lower flexibility, and rigid control patterns into a rigidity-like dimension.",
    "interpersonal_instability": "Aggregates relational ambivalence, boundary diffusion, negative audience effects, and uncertain-threat-driven interpersonal strain into a relationship-instability dimension.",
    "expressive_symbolization": "Aggregates imagery density, sensory grounding, affective implication, and abstract reflection into a qualitative style dimension that tracks indirect, symbolic, and aesthetically mediated expression.",
    "positive_engagement": "Aggregates positive tone, reward, social engagement, flexibility, and activation into a broad engagement/protective dimension.",
}


COMPUTATIONAL_AXIS_RATIONALES = {
    "dopaminergic_pressure": "Approximates reward drive, incentive salience, and action vigor. Higher values suggest more pull toward action and reward; lower values suggest blunted wanting or anhedonic flattening.",
    "control_allocation": "Approximates the expected value and availability of control. Higher values suggest the person can invest regulation where it matters; lower values suggest control is fragmented or costly to deploy.",
    "volatility_expectancy": "Approximates how much the person seems to expect instability or rapid changes. Higher values suggest a world model organized around unpredictability and abrupt shifts.",
    "prediction_error_weighting": "Approximates how strongly deviations, surprises, and cues seem to hit. Higher values suggest small signals are punching through with high gain rather than being absorbed in context.",
    "social_salience": "Approximates how strongly interpersonal approval, rejection, attraction, or belonging are organizing the current state. High values do not necessarily mean positive relationships, only that the social channel is carrying weight.",
    "effort_cost_load": "Approximates how metabolically costly action and self-regulation seem to feel. Higher values suggest more uphill effort and depletion.",
    "social_reward_coupling": "Approximates how strongly social context seems to modulate reward pursuit and performance. Higher values suggest other people are strongly shaping access to reward, motivation, or disruption.",
    "threat_hazard_expectancy": "Approximates how much rising uncertainty itself seems to be generating fear and avoidance before any concrete negative event arrives.",
    "agency_coherence": "Approximates whether awareness, boundaries, and intentional choice are hanging together as a coherent sense of agency rather than fragmenting under pressure.",
}


DOMAIN_KEYWORDS: dict[str, set[str]] = {
    "work_proficiency": {
        "boss",
        "career",
        "client",
        "coworker",
        "deadline",
        "job",
        "meeting",
        "office",
        "project",
        "promotion",
        "school",
        "study",
        "task",
        "team",
        "work",
    },
    "relationship_romance": {
        "boyfriend",
        "breakup",
        "date",
        "dated",
        "dating",
        "dating",
        "girlfriend",
        "husband",
        "intimacy",
        "intimate",
        "marriage",
        "men",
        "partner",
        "relationship",
        "romantic",
        "sex",
        "spouse",
        "women",
        "wife",
    },
    "family_social": {
        "brother",
        "community",
        "dad",
        "family",
        "friend",
        "friends",
        "mom",
        "mother",
        "people",
        "sister",
        "social",
        "son",
        "daughter",
    },
    "health_body": {
        "body",
        "diet",
        "eat",
        "energy",
        "exercise",
        "fitness",
        "food",
        "gym",
        "health",
        "ill",
        "nutrition",
        "pain",
        "sleep",
        "sick",
        "tired",
        "walk",
        "workout",
    },
    "faith_meaning": {
        "belief",
        "faith",
        "god",
        "meaning",
        "pray",
        "prayer",
        "purpose",
        "soul",
        "spiritual",
        "values",
    },
    "identity_integrity": {
        "character",
        "identity",
        "integrity",
        "myself",
        "person",
        "proud",
        "shame",
        "standard",
        "who i am",
    },
    "strategy_execution": {
        "goal",
        "habit",
        "organized",
        "plan",
        "planned",
        "routine",
        "schedule",
        "structure",
        "system",
    },
}


DOMAIN_LABELS = {
    "work_proficiency": "Work / proficiency",
    "relationship_romance": "Relationship / romance",
    "family_social": "Family / social",
    "health_body": "Health / body",
    "faith_meaning": "Faith / meaning",
    "identity_integrity": "Identity / integrity",
    "strategy_execution": "Strategy / execution",
}
